### ISSUE TITLE
Incorrect appearance on initial interface being shown.

### ISSUE THREAD

**Issue by heyitsbench** [r-o-b-o-t-o/Attune-3.3.5#2]
![image](https://github.com/r-o-b-o-t-o/Attune-3.3.5/assets/38561765/a4e2550c-a07f-4eb5-89df-a97d5772abb5)
Seems to happen very often when being shown something for the first time. Clicking onto an attunement like Onyxia's Lair and back to Molten Core will [show the data correctly](https://github.com/r-o-b-o-t-o/Attune-3.3.5/assets/38561765/c9b66a88-51d9-415c-ac96-2411648efba9).

**Comment by r-o-b-o-t-o** [comment]
Yep noticed that too, looking into it
