### ISSUE TITLE
feat: Add settings.

### ISSUE THREAD

**Issue by heyitsbench** [r-o-b-o-t-o/Attune-3.3.5#3]
Currently the addon has a settings page in the interface menu, but it has no actual options in it.

**Comment by r-o-b-o-t-o** [comment]
Works for me, do you get Lua errors?

**Comment by heyitsbench** [comment]
> Works for me, do you get Lua errors?

[Yes, I do](https://gist.github.com/heyitsbench/3d66ee7d63a826cf5e4b4992700c0dce) as a matter of fact.

**Comment by r-o-b-o-t-o** [comment]
> [Yes, I do](https://gist.github.com/heyitsbench/3d66ee7d63a826cf5e4b4992700c0dce) as a matter of fact.

That error should be fixed with 781d3c53293d334f674acb5c0d093acbe9306b40

**Comment by heyitsbench** [comment]
> That error should be fixed with [781d3c5](https://github.com/r-o-b-o-t-o/Attune-3.3.5/commit/781d3c53293d334f674acb5c0d093acbe9306b40)

Those errors did not seem to be the cause of the missing settings. No other Lua errors.
